import { prisma } from "./prisma";
import { translate } from "./translator";

const CONSONANTS = ["b", "c", "d", "g", "k", "m", "n", "r", "s", "t", "v", "sh", "dr", "tr", "kr"];
const VOWELS = ["a", "e", "i", "o", "u", "ar", "ir", "or", "al"];
const SUFFIXES = ["", "'ir", "'e", "ir", "e", "an", "'al"];

export function generateWord(seed: string): string {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  // Décalages non signés (>>>) : hash peut dépasser 2^31, un ">>" signé le rendrait
  // négatif et l'indexation de tableau retournerait alors `undefined`.
  const c1 = CONSONANTS[hash % CONSONANTS.length];
  const v1 = VOWELS[(hash >>> 4) % VOWELS.length];
  const c2 = CONSONANTS[(hash >>> 8) % CONSONANTS.length];
  const v2 = VOWELS[(hash >>> 12) % VOWELS.length];
  const suf = SUFFIXES[(hash >>> 16) % SUFFIXES.length];
  return c1 + v1 + c2 + v2 + suf;
}

export type WordOrigin = "dict" | "generated" | "unknown";
export type DetailedWord = { original: string; translated: string; origin: WordOrigin };
export type DetailedTranslation = {
  input: string; output: string; direction: "fr-to-mandoa" | "mandoa-to-fr"; words: DetailedWord[];
};

// Traduction "enrichie" : mêmes règles que translate(), mais les mots FR inconnus du
// dictionnaire se voient attribuer un mot mando'a crédible généré à la volée (et persisté,
// isAuto: true) plutôt que d'être laissés tels quels. Chaque mot du résultat porte son
// origine (dict / generated / unknown) pour permettre un rendu différencié côté UI.
export async function translateWithAutoGenerateDetailed(
  text: string,
  direction: "fr-to-mandoa" | "mandoa-to-fr" = "fr-to-mandoa",
): Promise<DetailedTranslation> {
  const entries = await prisma.dictionaryEntry.findMany({ select: { french: true, mandoa: true, isAuto: true } });
  const customFr: Record<string, string> = {};
  const customMa: Record<string, string> = {};
  const autoFrenchKeys = new Set<string>();
  for (const e of entries) {
    customFr[e.french.toLowerCase()] = e.mandoa;
    customMa[e.mandoa.toLowerCase()] = e.french;
    if (e.isAuto) autoFrenchKeys.add(e.french.toLowerCase());
  }

  if (direction === "mandoa-to-fr") {
    // Pas de génération dans ce sens : un mot mando'a inconnu reste une erreur.
    const result = translate(text, "mandoa-to-fr", customFr, customMa);
    return {
      input: result.input, output: result.output, direction: result.direction,
      words: result.words.map(w => ({ original: w.original, translated: w.translated, origin: w.found ? "dict" : "unknown" })),
    };
  }

  const result = translate(text, "fr-to-mandoa", customFr, customMa);

  // Pour chaque mot non trouvé, générer et sauvegarder
  const toCreate: Array<{ french: string; mandoa: string }> = [];
  const existingMandoa = new Set(Object.values(customFr));
  const generatedThisCall = new Set<string>();

  for (const w of result.words) {
    if (!w.found && w.original.trim() && /^[a-zA-ZÀ-ÿ]+$/.test(w.original)) {
      const key = w.original.toLowerCase();
      if (!customFr[key]) {
        let generated = generateWord(key);
        // Éviter les collisions
        let attempt = 0;
        while (existingMandoa.has(generated)) {
          generated = generateWord(key + attempt++);
        }
        existingMandoa.add(generated);
        customFr[key] = generated;
        generatedThisCall.add(key);
        toCreate.push({ french: key, mandoa: generated });
      }
    }
  }

  if (toCreate.length > 0) {
    for (const e of toCreate) {
      await prisma.dictionaryEntry.upsert({
        where: { french: e.french },
        create: { french: e.french, mandoa: e.mandoa, isAuto: true },
        update: {},
      });
    }
  }

  // Retraduit avec les nouveaux mots
  const finalResult = toCreate.length > 0 ? translate(text, "fr-to-mandoa", customFr, customMa) : result;

  const words: DetailedWord[] = finalResult.words.map(w => {
    if (!w.found) return { original: w.original, translated: w.translated, origin: "unknown" as const };
    const key = w.original.toLowerCase();
    const origin: WordOrigin = (autoFrenchKeys.has(key) || generatedThisCall.has(key)) ? "generated" : "dict";
    return { original: w.original, translated: w.translated, origin };
  });

  return { input: finalResult.input, output: finalResult.output, direction: finalResult.direction, words };
}

export async function translateWithAutoGenerate(text: string): Promise<string> {
  const result = await translateWithAutoGenerateDetailed(text, "fr-to-mandoa");
  return result.output;
}
