import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { translate } from "@/lib/translator";
import { translateWithAutoGenerateDetailed } from "@/lib/mandoa-auto";
import { prisma } from "@/lib/prisma";

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Non authentifie" }, { status: 401 });

  const user = await prisma.user.findUnique({ where: { id: session.user.id }, select: { mandalorien: true } });
  if (!user?.mandalorien) return NextResponse.json({ error: "Acces reserve aux Mandaloriens" }, { status: 403 });

  const { text, direction } = await req.json();
  if (!text?.trim()) return NextResponse.json({ error: "Texte vide" }, { status: 400 });

  // Direction auto-détectée : on laisse translate() trancher avant de router vers la
  // version enrichie (qui exige une direction explicite pour savoir si elle peut générer).
  const dir = direction === "fr-to-mandoa" || direction === "mandoa-to-fr"
    ? direction
    : translate(text.trim()).direction;

  const result = await translateWithAutoGenerateDetailed(text.trim(), dir);
  return NextResponse.json(result);
}
